export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function httpsUrl(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}}
export function spotifyId(value){try{const u=new URL(value);const match=u.pathname.match(/^\/album\/([A-Za-z0-9]{22})\/?$/);return u.protocol==='https:'&&u.hostname==='open.spotify.com'&&match?match[1]:'';}catch{return '';}}
export function albumMarkup(r){
 const esc=escapeHtml;const id=spotifyId(r.spotifyUrl);const tracks=Array.isArray(r.tracklist)?r.tracklist:[];const photos=Array.isArray(r.vinylPhotos)?r.vinylPhotos:[];
 return `<div class="album-overview"><img class="album-art" src="${esc(httpsUrl(r.cover))}" alt="${esc(r.title)} album cover" width="600" height="600"/><div><p class="eyebrow">RECORD ${String(r.rank).padStart(2,'0')} / ${esc(r.genre)}</p><h1>${esc(r.title)}</h1><p class="dialog-artist">${esc(r.artist)} · ${esc(r.year)}</p><p>${esc(r.note)}</p>${r.favoriteTrack?`<p class="track">A TRACK TO SIT WITH<br/><strong>${esc(r.favoriteTrack)}</strong></p>`:''}</div></div>
 <div class="album-listening"><section class="album-tracklist"><h2 class="eyebrow">THE TRACKLIST</h2>${r.tracklistEdition?`<p class="edition-label">${esc(r.tracklistEdition)}</p>`:''}<ol>${tracks.map((t,i)=>`<li><span class="track-position">${esc(t.position||String(i+1).padStart(2,'0'))}</span><span>${esc(t.title)}</span>${t.duration?`<span class="track-duration">${esc(t.duration)}</span>`:''}</li>`).join('')}</ol>${httpsUrl(r.tracklistSource)?`<a class="source-link" href="${esc(httpsUrl(r.tracklistSource))}" target="_blank" rel="noopener noreferrer">Tracklist source</a>`:''}</section>
 <section class="album-player"><h2 class="eyebrow">LISTEN ON SPOTIFY</h2>${id?`<iframe title="Listen to ${esc(r.title)} by ${esc(r.artist)} on Spotify" src="https://open.spotify.com/embed/album/${id}?utm_source=generator&theme=0" width="100%" height="352" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen loading="lazy"></iframe><a class="source-link" href="https://open.spotify.com/album/${id}" target="_blank" rel="noopener noreferrer">Open album in Spotify</a>`:''}</section></div>
 <section class="album-vinyl"><h2 class="eyebrow">ON VINYL</h2><p class="edition-label">${esc(r.vinylEdition||'Reference edition')}</p><div class="vinyl-photo-grid">${photos.map(p=>`<figure><a href="${esc(httpsUrl(p.url))}" target="_blank" rel="noopener noreferrer" aria-label="View ${esc(p.alt||r.title+' vinyl')} photograph"><img src="${esc(httpsUrl(p.url))}" alt="${esc(p.alt||r.title+' physical vinyl record')}" loading="lazy" width="800" height="600"/></a><figcaption>${esc(p.alt||'')}${httpsUrl(p.sourceUrl)?`<a href="${esc(httpsUrl(p.sourceUrl))}" target="_blank" rel="noopener noreferrer">Photo: ${esc(p.credit||'source')}</a>`:''}</figcaption></figure>`).join('')}</div></section>`;
}
